travis:
  secure:
    BINSTAR_TOKEN: dWvNJAofGKlwFBtfA+6I18gd3WVAYO07pQzlzduuMrehqQvMOJxd5ANF/O5D/qnAmt7p+hh3pFlWjkpqEXbatJ4ycvJo/oXbIzt22saGAWK0NCBjbg/PLGG8I7BnGQ28LW7PTQ92xHk1kjZ0fU+YSA8x1AwKiN+vOkfh6krmTpoMvRQEL9vMOBybHOTgm4qBHQg4+vQegsi07Nd5vOEo4nHuGJgD7SNUNnIOsQ+FFYa5WwpZKnYwmu9XMyJlX4cWs8GwWBH/DTCDJ+h2nWyycfa7LfoUVQaydE5TOYC6Tz4l5BKgtGITSOLh1mz2jsOlWj4hBcrtJnz9A2tTcTZk36Ks5YOez4CkMMxnsa2ti9C+56Fsp2cyUyf0wYrfRitqi7YLunYIgyK8ppjxEA9TQrPiCh48rbU8czbQyrpGu4+UShvmVMDsx4lzjjJCK4d3K4xOVCbDG8zIzXPlCDjqD/1Ig5zHEZXDEwKb/rOcOVanS/ZQkfDyYym4EmFx1UshTdZmr3dyCkf7FUtLg/oFUu0Q6ptOo+kk4+9mXRXke1WYXuGHmNb5GTaCHeMMny1ZzobU1o6gGQ+3WQnXOsXDSbgBJ2frhsQ9I+FBQbCRBsPcBfD1AOws5HSJ5t8UHvHNteUwFCjC6XTw1TIs2HSkOvpv3vhEMx02+iXKq5zGva0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
